                                                                                               Hurgland-Nick KELIET

                                               MATRICES ET NUMPY

# Import du module

In [1]:
import numpy as np

In [2]:
#Création de la matrice
matrice = np.array([[1,2],[3,4],[5,6]])

In [3]:
#Afficher la matrice
print(matrice)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
#Vérifier  les dimensions de la matrice
matrice.shape

(3, 2)

In [5]:
#Transposé de la matrice
matrice_transpose = matrice.T
print(matrice_transpose)

[[1 3 5]
 [2 4 6]]


In [6]:
# Dimension de la matrice transposé
matrice_transpose.shape

(2, 3)

# Opération sur les matrices

In [7]:
# On ne peut que additionner et soustraire les matrices qui sont de même taille
# Créons une matrices uniquement rempli que de 1, qui demande en paramètre les dimensions
matrice_2 = np.ones((3,2))
matrice_2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
matrice + matrice_2

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

# # Produit sur les matrices

In [9]:
# Le nombre de colonnes de la matrice a soit égale au nombre de lignes de la matrice b
# Exemple de produit qui ne fonctionne pas
matrice.dot(matrice_2)
# Il faudrait que les dimensions soit comme ceci par exemple (n,m)*(m,p)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
# Essayon de transposer la matrice_2
matrice.dot(matrice_2.T)

In [ ]:
# Explication
# Dimension matrice 1 "matrice"
matrice.shape

In [ ]:
# Dimension matrice 2 "matrice_2"
matrice_2.T.shape

## NB: Toujours noté les dimension de matrices